### ISSUE TITLE
Get Flutter Form Builder setup and working

### ISSUE THREAD

**Issue by bergmankyle99** [a307/tru-dawson-project#1]
here is package: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder

currently supports: 
FormBuilderCheckbox - Single checkbox field
FormBuilderCheckboxGroup - List of checkboxes for multiple selection
FormBuilderChoiceChip - Creates a chip that acts like a radio button.
FormBuilderDateRangePicker - For selection of a range of dates
FormBuilderDateTimePicker - For Date, Time and DateTime input
FormBuilderDropdown - Used to select one value from a list as a Dropdown
FormBuilderFilterChip - Creates a chip that acts like a checkbox
FormBuilderRadioGroup - Used to select one value from a list of Radio Widgets
FormBuilderRangeSlider - Used to select a range from a range of values
FormBuilderSlider - For selection of a numerical value on a slider
FormBuilderSwitch - On/Off switch field
FormBuilderTextField - A Material Design text field input

**Comment by elizabethranta** [comment]
Got it running in LizBranch, feel free to clone and test, you will have to run some lines in terminal but they are commented.
