### ISSUE TITLE
Offline Capabilities

### ISSUE THREAD

**Issue by a307** [a307/tru-dawson-project#25]

**Comment by a307** [comment]
we only need app - photos and signatures don't link url to cloud firestore

**Comment by bergmankyle99** [comment]
Added offline sign in which takes the most recent signed in user and allows them to sign in without having internet connection

**Comment by bergmankyle99** [comment]
Sometimes the form data for generating forms does not come through on offline mode on IOS. Sometimes it does, odd.

**Comment by bergmankyle99** [comment]
offline working for IOS

**Comment by a307** [comment]
offline works for everything but images (signatures, images, maps)
