### ISSUE TITLE
IOS functionality tested

### ISSUE THREAD

**Issue by a307** [a307/tru-dawson-project#27]

**Comment by elizabethranta** [comment]
Trying to get IOS emulator going- 
Smartface won't send email to download off their website: https://smartface.io/
moving on to other options

**Comment by elizabethranta** [comment]
Xcode- Requires recent Mac to download
Smartface - Download instructions inaccessable (website won't send email)
Xamarin - requires Mac first. 
Appetize - Requires build made with Xcode or Xamarin first, then emulates it.

**Comment by a307** [comment]
Attempting to use Apollo with remote desktop but may just switch android

**Comment by a307** [comment]
set up mac mini still not entriely working

**Comment by a307** [comment]
trouble connecting with firebase

**Comment by a307** [comment]
we all gonna work on it but it sucks >:(

**Comment by bergmankyle99** [comment]
I have taken over IOS and have got it running our application. Still working on testing features and then I will close out.

**Comment by bergmankyle99** [comment]
IOS is tested and working with firebase. Offline is still a little wierd but that is for https://github.com/a307/tru-dawson-project/issues/25
